version: '3.3'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"

  db:
    container_name: pg_db
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/

  api:
    container_name: api
    build: .
    entrypoint: ./docker-entrypoint.sh
    ports:
      - "8080:8000"
    environment:
      - WAIT_HOSTS=redis:6379
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - api:/app/repository/migration/versions

volumes:
  db:
    driver: local
  api:
    driver: local
  redis:
    driver: local